"""
VigiliCloud API — application entry point.

Only contains: app init, CORS middleware, startup hook, /health, /
All business logic lives in:
  app/config.py   — env vars & constants
  app/deps.py     — shared helpers, models, DB helpers
  app/routers/    — auth, billing, scans, accounts, fix_guidance
"""
from __future__ import annotations

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.config import (
    APP_ENV,
    COOKIE_SECURE,
    CORS_ORIGINS,
    FRONTEND_URL,
    SCAN_SCHEDULE_HOURS,
)
from app.deps import (
    _do_seed_fix_guidance,
    init_db,
    razorpay_config_summary,
    run_scheduled_scans,
)
from app.routers import accounts, approvals, auth, billing, developer, fix_guidance, integrations, msp, scans

# ---------------------------------------------------------------------------
# Startup — db init, seed data, scheduler
# ---------------------------------------------------------------------------

def ensure_auth_tables() -> None:
    """Create users / auth_sessions / billing_webhook_events tables and seed admin."""
    import sqlite3
    from app.config import USE_POSTGRES, DEFAULT_ADMIN_EMAIL, DEFAULT_ADMIN_PASSWORD, DEFAULT_ADMIN_NAME
    from app.deps import get_conn, hash_password, now_utc_iso

    conn = get_conn()
    cur = conn.cursor()

    if USE_POSTGRES:
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                name TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'admin',
                created_at TEXT NOT NULL
            )
            """
        )
    else:
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                name TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'admin',
                created_at TEXT NOT NULL
            )
            """
        )

    def _add_col_if_missing(column_name: str, ddl: str) -> None:
        rows = conn.execute("PRAGMA table_info(users)").fetchall()
        cols = [str(r["name"]) for r in rows]
        if column_name not in cols:
            conn.execute(f"ALTER TABLE users ADD COLUMN {ddl}")

    _add_col_if_missing("subscription_status", "subscription_status TEXT NOT NULL DEFAULT 'free'")
    _add_col_if_missing("stripe_customer_id", "stripe_customer_id TEXT NOT NULL DEFAULT ''")
    _add_col_if_missing("stripe_subscription_id", "stripe_subscription_id TEXT NOT NULL DEFAULT ''")
    _add_col_if_missing("scheduled_scans_enabled", "scheduled_scans_enabled INTEGER NOT NULL DEFAULT 0")
    _add_col_if_missing("slack_webhook_url", "slack_webhook_url TEXT NOT NULL DEFAULT ''")
    _add_col_if_missing("jira_url", "jira_url TEXT NOT NULL DEFAULT ''")
    _add_col_if_missing("jira_email", "jira_email TEXT NOT NULL DEFAULT ''")
    _add_col_if_missing("jira_api_token", "jira_api_token TEXT NOT NULL DEFAULT ''")
    _add_col_if_missing("jira_project_key", "jira_project_key TEXT NOT NULL DEFAULT ''")
    _add_col_if_missing("github_token", "github_token TEXT NOT NULL DEFAULT ''")
    _add_col_if_missing("github_default_repo", "github_default_repo TEXT NOT NULL DEFAULT ''")

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS auth_sessions (
            session_token TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            expires_at TEXT NOT NULL
        )
        """
    )

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS billing_webhook_events (
            event_id TEXT PRIMARY KEY,
            event_type TEXT NOT NULL,
            livemode INTEGER NOT NULL DEFAULT 0,
            customer_id TEXT NOT NULL DEFAULT '',
            subscription_id TEXT NOT NULL DEFAULT '',
            status TEXT NOT NULL DEFAULT 'received',
            error_message TEXT NOT NULL DEFAULT '',
            payload_json TEXT NOT NULL,
            received_at TEXT NOT NULL,
            processed_at TEXT NOT NULL DEFAULT ''
        )
        """
    )

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS api_keys (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            key_hash TEXT NOT NULL UNIQUE,
            key_prefix TEXT NOT NULL,
            label TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            last_used_at TEXT NOT NULL DEFAULT '',
            is_active INTEGER NOT NULL DEFAULT 1
        )
        """
    )

    conn.commit()

    cur.execute("SELECT id FROM users WHERE lower(email) = lower(?)", (DEFAULT_ADMIN_EMAIL,))
    if not cur.fetchone():
        cur.execute(
            """
            INSERT INTO users (
                email, password_hash, name, role, created_at,
                subscription_status, stripe_customer_id, stripe_subscription_id
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                DEFAULT_ADMIN_EMAIL,
                hash_password(DEFAULT_ADMIN_PASSWORD),
                DEFAULT_ADMIN_NAME,
                "admin",
                now_utc_iso(),
                "free",
                "",
                "",
            ),
        )
        conn.commit()

    conn.close()


@asynccontextmanager
async def lifespan(app: FastAPI):
    init_db()
    ensure_auth_tables()
    _do_seed_fix_guidance()

    if SCAN_SCHEDULE_HOURS > 0:
        try:
            from apscheduler.schedulers.background import BackgroundScheduler
            scheduler = BackgroundScheduler()
            scheduler.add_job(
                run_scheduled_scans,
                "interval",
                hours=SCAN_SCHEDULE_HOURS,
                id="scheduled_scans",
                replace_existing=True,
            )
            scheduler.start()
        except Exception:
            pass

    yield  # app runs here


# ---------------------------------------------------------------------------
# App & middleware
# ---------------------------------------------------------------------------

app = FastAPI(title="VigiliCloud API", version="0.4.0", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Core routes
# ---------------------------------------------------------------------------

@app.api_route("/health", methods=["GET", "HEAD"])
def health():
    rz_info = razorpay_config_summary()
    return {
        "ok": True,
        "app_env": APP_ENV,
        "frontend_url": FRONTEND_URL,
        "cookie_secure": COOKIE_SECURE,
        "cors_origins": CORS_ORIGINS,
        "razorpay": {
            "configured": rz_info["configured"],
            "webhook_configured": rz_info["webhook_configured"],
            "checkout_ready": rz_info["checkout_ready"],
        },
    }


@app.get("/")
def root():
    return {
        "name": "VigiliCloud API",
        "version": "0.4.0",
        "app_env": APP_ENV,
        "frontend_url": FRONTEND_URL,
        "auth": "enabled",
        "billing": "deployment_ready",
    }


# ---------------------------------------------------------------------------
# Routers
# ---------------------------------------------------------------------------

app.include_router(auth.router)
app.include_router(billing.router)
app.include_router(scans.router)
app.include_router(accounts.router)
app.include_router(fix_guidance.router)
app.include_router(approvals.router)
app.include_router(developer.router)
app.include_router(integrations.router)
app.include_router(msp.router)
