from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import psycopg
from psycopg.rows import dict_row

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()


def now_utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _normalize_sql(sql: str) -> str:
    return sql.replace("?", "%s")


class PGCursorWrapper:
    def __init__(self, cursor: Any):
        self._cursor = cursor

    def execute(self, sql: str, params: tuple | list | None = None):
        sql = sql.strip()

        pragma_match = re.match(r"PRAGMA\s+table_info\(([\w_]+)\)", sql, re.IGNORECASE)
        if pragma_match:
            table_name = pragma_match.group(1)
            self._cursor.execute(
                """
                SELECT
                    ordinal_position AS cid,
                    column_name AS name,
                    data_type AS type
                FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = %s
                ORDER BY ordinal_position
                """,
                (table_name,),
            )
            return self

        self._cursor.execute(_normalize_sql(sql), params or ())
        return self

    def fetchone(self):
        row = self._cursor.fetchone()
        return dict(row) if row is not None else None

    def fetchall(self):
        rows = self._cursor.fetchall()
        return [dict(r) for r in rows]

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount


class PGConnectionWrapper:
    def __init__(self, conn: Any):
        self._conn = conn
        self.row_factory = None

    def cursor(self) -> PGCursorWrapper:
        return PGCursorWrapper(self._conn.cursor())

    def execute(self, sql: str, params: tuple | list | None = None) -> PGCursorWrapper:
        cur = self.cursor()
        cur.execute(sql, params or ())
        return cur

    def commit(self) -> None:
        self._conn.commit()

    def close(self) -> None:
        self._conn.close()


def get_conn() -> PGConnectionWrapper:
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL is required for Postgres mode")
    conn = psycopg.connect(DATABASE_URL, row_factory=dict_row)
    return PGConnectionWrapper(conn)


def row_to_dict(row: Optional[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    return dict(row) if row else None


def rows_to_dicts(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    return [dict(r) for r in rows]


def add_column_if_missing(conn: PGConnectionWrapper, table_name: str, column_name: str, ddl: str) -> None:
    rows = conn.execute(f"PRAGMA table_info({table_name})").fetchall()
    cols = [str(r["name"]) for r in rows]
    if column_name not in cols:
        conn.execute(f"ALTER TABLE {table_name} ADD COLUMN {ddl}")
    conn.commit()


def init_db() -> None:
    conn = get_conn()
    cur = conn.cursor()

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS scans (
            scan_id TEXT PRIMARY KEY,
            status TEXT NOT NULL,
            created_at TEXT NOT NULL,
            user_id INTEGER NOT NULL DEFAULT 1
        )
        """
    )

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS findings (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            scan_id TEXT NOT NULL,
            service TEXT,
            severity TEXT,
            check_id TEXT,
            title TEXT,
            resource_id TEXT,
            status TEXT,
            created_at TEXT NOT NULL,
            evidence TEXT
        )
        """
    )

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS fix_guidance (
            check_id TEXT PRIMARY KEY,
            title TEXT NOT NULL,
            summary TEXT NOT NULL,
            console_path TEXT NOT NULL,
            steps_json TEXT NOT NULL,
            cli_json TEXT NOT NULL,
            terraform TEXT NOT NULL DEFAULT '',
            updated_at TEXT NOT NULL
        )
        """
    )

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS finding_actions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            scan_id TEXT NOT NULL,
            check_id TEXT NOT NULL,
            resource_id TEXT NOT NULL,
            resolution TEXT NOT NULL,
            note TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            UNIQUE(scan_id, check_id, resource_id)
        )
        """
    )

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS connected_accounts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL DEFAULT 1,
            customer_name TEXT NOT NULL,
            account_name TEXT NOT NULL DEFAULT '',
            aws_account_id TEXT NOT NULL,
            role_arn TEXT NOT NULL,
            external_id TEXT NOT NULL DEFAULT '',
            region TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'PENDING',
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )

    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS scan_account_links (
            scan_id TEXT PRIMARY KEY,
            account_id INTEGER NOT NULL,
            customer_name TEXT NOT NULL,
            account_name TEXT NOT NULL DEFAULT '',
            aws_account_id TEXT NOT NULL,
            role_arn TEXT NOT NULL,
            region TEXT NOT NULL,
            linked_at TEXT NOT NULL
        )
        """
    )

    conn.commit()

    # migrations for existing tables that predate these columns
    add_column_if_missing(conn, "connected_accounts", "user_id", "user_id INTEGER NOT NULL DEFAULT 1")
    add_column_if_missing(conn, "scans", "user_id", "user_id INTEGER NOT NULL DEFAULT 1")

    conn.close()


def save_scan(scan_id: str, status: str) -> None:
    conn = get_conn()
    conn.execute(
        """
        INSERT INTO scans (scan_id, status, created_at)
        VALUES (?, ?, ?)
        ON CONFLICT (scan_id)
        DO UPDATE SET status = EXCLUDED.status
        """,
        (scan_id, status, now_utc_iso()),
    )
    conn.commit()
    conn.close()


def update_scan_user_id(scan_id: str, user_id: int) -> None:
    conn = get_conn()
    conn.execute(
        "UPDATE scans SET user_id = ? WHERE scan_id = ?",
        (user_id, scan_id),
    )
    conn.commit()
    conn.close()


def save_findings(scan_id: str, findings: List[Dict[str, Any]]) -> None:
    conn = get_conn()
    conn.execute("DELETE FROM findings WHERE scan_id = ?", (scan_id,))

    for f in findings:
        conn.execute(
            """
            INSERT INTO findings (
                scan_id,
                service,
                severity,
                check_id,
                title,
                resource_id,
                status,
                created_at,
                evidence
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                scan_id,
                f.get("service", ""),
                f.get("severity", ""),
                f.get("check_id", ""),
                f.get("title", ""),
                f.get("resource_id", ""),
                f.get("status", ""),
                f.get("created_at", now_utc_iso()),
                json.dumps(f.get("evidence", {})),
            ),
        )

    conn.commit()
    conn.close()


def get_scan(scan_id: str) -> Optional[Dict[str, Any]]:
    conn = get_conn()
    row = conn.execute(
        "SELECT scan_id, status, created_at, user_id FROM scans WHERE scan_id = ?",
        (scan_id,),
    ).fetchone()
    conn.close()
    return row_to_dict(row)


def get_findings(scan_id: str) -> List[Dict[str, Any]]:
    conn = get_conn()
    rows = conn.execute(
        """
        SELECT
            id,
            scan_id,
            service,
            severity,
            check_id,
            title,
            resource_id,
            status,
            created_at,
            evidence
        FROM findings
        WHERE scan_id = ?
        ORDER BY id ASC
        """,
        (scan_id,),
    ).fetchall()
    conn.close()

    out: List[Dict[str, Any]] = []
    for r in rows:
        item = dict(r)
        raw_evidence = item.get("evidence")
        try:
            item["evidence"] = json.loads(raw_evidence) if raw_evidence else {}
        except Exception:
            item["evidence"] = {}
        out.append(item)
    return out


def list_scans(limit: int = 50, account_id: Optional[int] = None, user_id: Optional[int] = None) -> List[Dict[str, Any]]:
    conn = get_conn()

    if account_id is not None:
        rows = conn.execute(
            """
            SELECT
                s.scan_id,
                s.status,
                s.created_at,
                l.account_id,
                l.customer_name,
                l.account_name,
                l.aws_account_id,
                l.role_arn,
                l.region,
                l.linked_at
            FROM scans s
            LEFT JOIN scan_account_links l ON l.scan_id = s.scan_id
            WHERE l.account_id = ?
              AND (? IS NULL OR s.user_id = ?)
            ORDER BY s.created_at DESC
            LIMIT ?
            """,
            (account_id, user_id, user_id, limit),
        ).fetchall()
    elif user_id is not None:
        rows = conn.execute(
            """
            SELECT
                s.scan_id,
                s.status,
                s.created_at,
                l.account_id,
                l.customer_name,
                l.account_name,
                l.aws_account_id,
                l.role_arn,
                l.region,
                l.linked_at
            FROM scans s
            LEFT JOIN scan_account_links l ON l.scan_id = s.scan_id
            WHERE s.user_id = ?
            ORDER BY s.created_at DESC
            LIMIT ?
            """,
            (user_id, limit),
        ).fetchall()
    else:
        rows = conn.execute(
            """
            SELECT
                s.scan_id,
                s.status,
                s.created_at,
                l.account_id,
                l.customer_name,
                l.account_name,
                l.aws_account_id,
                l.role_arn,
                l.region,
                l.linked_at
            FROM scans s
            LEFT JOIN scan_account_links l ON l.scan_id = s.scan_id
            ORDER BY s.created_at DESC
            LIMIT ?
            """,
            (limit,),
        ).fetchall()

    conn.close()
    return rows_to_dicts(rows)


def get_fix_guidance(check_id: str) -> Optional[Dict[str, Any]]:
    conn = get_conn()
    row = conn.execute(
        """
        SELECT
            check_id,
            title,
            summary,
            console_path,
            steps_json,
            cli_json,
            terraform,
            updated_at
        FROM fix_guidance
        WHERE check_id = ?
        """,
        (check_id,),
    ).fetchone()
    conn.close()

    if not row:
        return None

    return {
        "check_id": row["check_id"],
        "title": row["title"],
        "summary": row["summary"],
        "consolePath": row["console_path"],
        "steps": json.loads(row["steps_json"]) if row.get("steps_json") else [],
        "cli": json.loads(row["cli_json"]) if row.get("cli_json") else [],
        "terraform": row.get("terraform", "") or "",
        "updated_at": row["updated_at"],
    }


def upsert_fix_guidance(
    check_id: str,
    title: str,
    summary: str,
    console_path: str,
    steps: List[str],
    cli: List[str],
    terraform: str,
) -> None:
    conn = get_conn()
    conn.execute(
        """
        INSERT INTO fix_guidance (
            check_id,
            title,
            summary,
            console_path,
            steps_json,
            cli_json,
            terraform,
            updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT (check_id)
        DO UPDATE SET
            title = EXCLUDED.title,
            summary = EXCLUDED.summary,
            console_path = EXCLUDED.console_path,
            steps_json = EXCLUDED.steps_json,
            cli_json = EXCLUDED.cli_json,
            terraform = EXCLUDED.terraform,
            updated_at = EXCLUDED.updated_at
        """,
        (
            check_id,
            title,
            summary,
            console_path,
            json.dumps(steps),
            json.dumps(cli),
            terraform or "",
            now_utc_iso(),
        ),
    )
    conn.commit()
    conn.close()


def get_actions(scan_id: str) -> List[Dict[str, Any]]:
    conn = get_conn()
    rows = conn.execute(
        """
        SELECT
            scan_id,
            check_id,
            resource_id,
            resolution,
            note,
            created_at AS updated_at
        FROM finding_actions
        WHERE scan_id = ?
        ORDER BY created_at DESC
        """,
        (scan_id,),
    ).fetchall()
    conn.close()
    return rows_to_dicts(rows)


def upsert_action(
    scan_id: str,
    check_id: str,
    resource_id: str,
    resolution: str,
    note: str,
) -> None:
    conn = get_conn()
    conn.execute(
        """
        INSERT INTO finding_actions (
            scan_id,
            check_id,
            resource_id,
            resolution,
            note,
            created_at
        )
        VALUES (?, ?, ?, ?, ?, ?)
        ON CONFLICT (scan_id, check_id, resource_id)
        DO UPDATE SET
            resolution = EXCLUDED.resolution,
            note = EXCLUDED.note,
            created_at = EXCLUDED.created_at
        """,
        (
            scan_id,
            check_id,
            resource_id,
            resolution,
            note,
            now_utc_iso(),
        ),
    )
    conn.commit()
    conn.close()


def create_connected_account(
    user_id: int,
    customer_name: str,
    account_name: str,
    aws_account_id: str,
    role_arn: str,
    external_id: str,
    region: str,
    status: str = "PENDING",
    is_active: bool = True,
) -> int:
    conn = get_conn()
    row = conn.execute(
        """
        INSERT INTO connected_accounts (
            user_id,
            customer_name,
            account_name,
            aws_account_id,
            role_arn,
            external_id,
            region,
            status,
            is_active,
            created_at,
            updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        RETURNING id
        """,
        (
            user_id,
            customer_name,
            account_name,
            aws_account_id,
            role_arn,
            external_id,
            region,
            status,
            is_active,
            now_utc_iso(),
            now_utc_iso(),
        ),
    ).fetchone()
    conn.commit()
    conn.close()
    return int(row["id"])


def list_connected_accounts(user_id: Optional[int] = None) -> List[Dict[str, Any]]:
    conn = get_conn()
    if user_id is not None:
        rows = conn.execute(
            """
            SELECT
                id,
                user_id,
                customer_name,
                account_name,
                aws_account_id,
                role_arn,
                external_id,
                region,
                status,
                is_active,
                created_at,
                updated_at
            FROM connected_accounts
            WHERE user_id = ?
            ORDER BY created_at DESC
            """,
            (user_id,),
        ).fetchall()
    else:
        rows = conn.execute(
            """
            SELECT
                id,
                user_id,
                customer_name,
                account_name,
                aws_account_id,
                role_arn,
                external_id,
                region,
                status,
                is_active,
                created_at,
                updated_at
            FROM connected_accounts
            ORDER BY created_at DESC
            """
        ).fetchall()
    conn.close()
    return rows_to_dicts(rows)


def get_connected_account(account_id: int, user_id: Optional[int] = None) -> Optional[Dict[str, Any]]:
    conn = get_conn()
    if user_id is not None:
        row = conn.execute(
            """
            SELECT
                id,
                user_id,
                customer_name,
                account_name,
                aws_account_id,
                role_arn,
                external_id,
                region,
                status,
                is_active,
                created_at,
                updated_at
            FROM connected_accounts
            WHERE id = ? AND user_id = ?
            """,
            (account_id, user_id),
        ).fetchone()
    else:
        row = conn.execute(
            """
            SELECT
                id,
                user_id,
                customer_name,
                account_name,
                aws_account_id,
                role_arn,
                external_id,
                region,
                status,
                is_active,
                created_at,
                updated_at
            FROM connected_accounts
            WHERE id = ?
            """,
            (account_id,),
        ).fetchone()
    conn.close()
    return row_to_dict(row)


def update_connected_account(
    account_id: int,
    user_id: int,
    customer_name: str,
    account_name: str,
    aws_account_id: str,
    role_arn: str,
    external_id: str,
    region: str,
    status: str,
    is_active: bool,
) -> bool:
    conn = get_conn()
    cur = conn.execute(
        """
        UPDATE connected_accounts
        SET
            customer_name = ?,
            account_name = ?,
            aws_account_id = ?,
            role_arn = ?,
            external_id = ?,
            region = ?,
            status = ?,
            is_active = ?,
            updated_at = ?
        WHERE id = ? AND user_id = ?
        """,
        (
            customer_name,
            account_name,
            aws_account_id,
            role_arn,
            external_id,
            region,
            status,
            is_active,
            now_utc_iso(),
            account_id,
            user_id,
        ),
    )
    conn.commit()
    updated = cur.rowcount > 0
    conn.close()
    return updated


def update_connected_account_status(account_id: int, status: str) -> None:
    conn = get_conn()
    conn.execute(
        """
        UPDATE connected_accounts
        SET status = ?, updated_at = ?
        WHERE id = ?
        """,
        (status, now_utc_iso(), account_id),
    )
    conn.commit()
    conn.close()


def delete_connected_account(account_id: int, user_id: Optional[int] = None) -> bool:
    conn = get_conn()

    if user_id is not None:
        existing = conn.execute(
            "SELECT id FROM connected_accounts WHERE id = ? AND user_id = ?",
            (account_id, user_id),
        ).fetchone()
    else:
        existing = conn.execute(
            "SELECT id FROM connected_accounts WHERE id = ?",
            (account_id,),
        ).fetchone()

    if not existing:
        conn.close()
        return False

    linked = conn.execute(
        "SELECT 1 FROM scan_account_links WHERE account_id = ? LIMIT 1",
        (account_id,),
    ).fetchone()
    if linked:
        conn.close()
        raise ValueError("Cannot delete account because scans already exist for this account")

    conn.execute("DELETE FROM connected_accounts WHERE id = ?", (account_id,))
    conn.commit()
    conn.close()
    return True


def save_scan_account_link(scan_id: str, account: Dict[str, Any]) -> None:
    conn = get_conn()
    conn.execute(
        """
        INSERT INTO scan_account_links (
            scan_id,
            account_id,
            customer_name,
            account_name,
            aws_account_id,
            role_arn,
            region,
            linked_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT (scan_id)
        DO UPDATE SET
            account_id = EXCLUDED.account_id,
            customer_name = EXCLUDED.customer_name,
            account_name = EXCLUDED.account_name,
            aws_account_id = EXCLUDED.aws_account_id,
            role_arn = EXCLUDED.role_arn,
            region = EXCLUDED.region,
            linked_at = EXCLUDED.linked_at
        """,
        (
            scan_id,
            account["id"],
            account.get("customer_name", ""),
            account.get("account_name", ""),
            account.get("aws_account_id", ""),
            account.get("role_arn", ""),
            account.get("region", "us-east-1"),
            now_utc_iso(),
        ),
    )
    conn.commit()
    conn.close()


def get_scan_account_link(scan_id: str) -> Optional[Dict[str, Any]]:
    conn = get_conn()
    row = conn.execute(
        """
        SELECT
            scan_id,
            account_id,
            customer_name,
            account_name,
            aws_account_id,
            role_arn,
            region,
            linked_at
        FROM scan_account_links
        WHERE scan_id = ?
        """,
        (scan_id,),
    ).fetchone()
    conn.close()
    return row_to_dict(row)
